### ISSUE TITLE
Informar a data quando o ICP for gerado.

### ISSUE THREAD

**Issue by romerlrl** [brosquinha/ICP#20]
Por exemplo substituindo isso `<!-- Artigo gerado pelo ICP -->` por `<!-- Artigo gerado pelo ICP em 2018 02 31-->`. Dessa maneira, chamará a atenção de quem estiver editando um artigo para uma lista de aparições e fontes muito defasada.

**Comment by brosquinha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Selecionar Eras Legends](https://trello.com/c/nl1bRos1/8-selecionar-eras-legends)

**Comment by brosquinha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Importar alguns dados via JSON externo](https://trello.com/c/0xC9P4Tp/9-importar-alguns-dados-via-json-externo)

**Comment by brosquinha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mostrar indicador dos passos](https://trello.com/c/lpox6I4J/6-mostrar-indicador-dos-passos)

**Comment by brosquinha** [comment]
Resolvido por #28
